//! # codegen — ContractualGoal から Rust コードを生成するモジュール
//!
//! ## 設計方針
//! - `ContractualGoal` の述語 AST を走査し、変数名・制約を抽出する
//! - hammurabi イディオム（`LogicRail::bind` + `Verifier`）に沿ったスケルトンを生成する
//! - 生成コードは **コンパイル可能な出発点** であり、型と実装は開発者が埋める
//!
//! ## 生成の流れ
//! ```text
//! ContractualGoal
//!   ↓ extract_variables()   — Predicate AST から (変数名, 制約コード[]) を収集
//!   ↓ emit_doc_comment()    — 契約を Rustdoc 形式で出力
//!   ↓ emit_signature()      — fn <name><V: Verifier>(...) -> Result<...>
//!   ↓ emit_body()           — LogicRail::bind 群 + todo!()
//! CodegenOutput { source: String }
//! ```

#[cfg(not(target_arch = "wasm32"))]
use std::path::Path;
use crate::lang::goal::{ContractualGoal, ForbiddenPattern, Predicate};

// ---------------------------------------------------------------------------
// VarInfo — 述語 AST から抽出した変数ひとつ分の情報
// ---------------------------------------------------------------------------

/// 述語から抽出した「変数 + その変数に課される制約コード文字列のリスト」。
#[derive(Debug, Clone)]
struct VarInfo {
    /// Rust 識別子として使える変数名
    name: String,
    /// `Constraint::Xxx { ... }` の形式のコード文字列
    constraints: Vec<String>,
}

// ---------------------------------------------------------------------------
// 変数抽出ロジック
// ---------------------------------------------------------------------------

/// `Predicate` の木を再帰的に走査して `VarInfo` を収集する。
/// 同じ変数名が複数の述語に登場した場合は制約をマージする。
fn extract_variables(predicates: &[Predicate]) -> Vec<VarInfo> {
    let mut vars: Vec<VarInfo> = Vec::new();

    for pred in predicates {
        collect_pred(pred, &mut vars);
    }
    vars
}

fn collect_pred(pred: &Predicate, vars: &mut Vec<VarInfo>) {
    match pred {
        Predicate::NonNull(var) => {
            upsert(vars, var, "Constraint::NonNull".into());
        }
        Predicate::InRange { var, min, max } => {
            upsert(
                vars,
                var,
                format!("Constraint::InRange {{ min: {min}_i64, max: {max}_i64 }}"),
            );
        }
        Predicate::Equals(a, b) => {
            upsert(
                vars,
                a,
                format!("Constraint::ConsistentWith(\"{b}\".into())"),
            );
        }
        // 複合述語は再帰的に展開
        Predicate::And(l, r) | Predicate::Or(l, r) | Predicate::Implies(l, r) => {
            collect_pred(l, vars);
            collect_pred(r, vars);
        }
        Predicate::Not(p) => collect_pred(p, vars),
        Predicate::ForAll { body, .. } | Predicate::Exists { body, .. } => {
            collect_pred(body, vars);
        }
        // Atom / True / False は変数を持たない
        Predicate::Atom(_) | Predicate::True | Predicate::False => {}
    }
}

/// 変数リストに upsert する（既存なら制約を追記、なければ新規挿入）。
fn upsert(vars: &mut Vec<VarInfo>, name: &str, constraint: String) {
    if let Some(v) = vars.iter_mut().find(|v| v.name == name) {
        if !v.constraints.contains(&constraint) {
            v.constraints.push(constraint);
        }
    } else {
        vars.push(VarInfo {
            name: name.to_owned(),
            constraints: vec![constraint],
        });
    }
}

// ---------------------------------------------------------------------------
// CodeGenerator — 生成エントリポイント
// ---------------------------------------------------------------------------

/// `ContractualGoal` → Rust コードのスケルトンを生成するジェネレーター。
///
/// # 使い方
/// ```rust,ignore
/// use hammurabi::codegen::CodeGenerator;
/// use hammurabi::lang::goal::{ContractualGoal, Predicate};
///
/// let goal = ContractualGoal::new("safe_division")
///     .require(Predicate::non_null("divisor"))
///     .require(Predicate::in_range("divisor", 1, i64::MAX))
///     .ensure(Predicate::atom("result_is_finite"));
///
/// let output = CodeGenerator::new().generate(&goal);
/// println!("{}", output.source());
/// output.save_to_file("src/safe_division.rs").unwrap();
/// ```
#[derive(Debug, Default)]
pub struct CodeGenerator;

impl CodeGenerator {
    pub fn new() -> Self {
        Self
    }

    /// `ContractualGoal` から `CodegenOutput` を生成する。
    pub fn generate(&self, goal: &ContractualGoal) -> CodegenOutput {
        let mut buf = String::new();

        self.emit_file_header(&mut buf, goal);
        self.emit_doc_comment(&mut buf, goal);
        self.emit_signature(&mut buf, goal);
        self.emit_body(&mut buf, goal);

        CodegenOutput { source: buf }
    }

    // -----------------------------------------------------------------------
    // ファイルヘッダー
    // -----------------------------------------------------------------------

    fn emit_file_header(&self, buf: &mut String, goal: &ContractualGoal) {
        buf.push_str("//! Generated by Hammurabi — do not edit manually.\n");
        buf.push_str("//! Edit the `ContractualGoal` definition instead.\n");
        buf.push_str("//!\n");
        buf.push_str(&format!(
            "//! ContractualGoal: `{}`\n",
            goal.name
        ));
        buf.push('\n');
        buf.push_str("#![allow(unused_variables, dead_code)]\n");
        buf.push('\n');
        buf.push_str("use hammurabi::compiler::verifier::{Verifier, VerificationError};\n");
        buf.push_str("use hammurabi::lang::rail::{Constraint, LogicRail};\n");
        buf.push('\n');
    }

    // -----------------------------------------------------------------------
    // doc コメント（契約の全条件を Rustdoc 形式で）
    // -----------------------------------------------------------------------

    fn emit_doc_comment(&self, buf: &mut String, goal: &ContractualGoal) {
        buf.push_str(&format!("/// # Contract: `{}`\n", goal.name));
        buf.push_str("///\n");
        buf.push_str("/// *Generated by [Hammurabi](https://github.com/hammurabi-lang/hammurabi)*\n");
        buf.push_str("///\n");

        // 事前条件
        buf.push_str("/// ## Preconditions — 呼び出し元が保証すること\n");
        if goal.preconditions.is_empty() {
            buf.push_str("/// *(なし)*\n");
        } else {
            for pre in &goal.preconditions {
                buf.push_str(&format!("/// - `{pre}`\n"));
            }
        }
        buf.push_str("///\n");

        // 事後条件
        buf.push_str("/// ## Postconditions — この関数が保証すること\n");
        if goal.postconditions.is_empty() {
            buf.push_str("/// *(なし)*\n");
        } else {
            for post in &goal.postconditions {
                buf.push_str(&format!("/// - `{post}`\n"));
            }
        }
        buf.push_str("///\n");

        // 不変条件
        if !goal.invariants.is_empty() {
            buf.push_str("/// ## Invariants — 実行中ずっと成立すること\n");
            for inv in &goal.invariants {
                buf.push_str(&format!("/// - `{inv}`\n"));
            }
            buf.push_str("///\n");
        }

        // 禁止パターン
        buf.push_str("/// ## Forbidden Patterns\n");
        for fp in &goal.forbidden {
            let desc = forbidden_description(fp);
            buf.push_str(&format!("/// - `{fp}` — {desc}\n"));
        }
        buf.push_str("///\n");
    }

    // -----------------------------------------------------------------------
    // 関数シグネチャ
    // -----------------------------------------------------------------------

    fn emit_signature(&self, buf: &mut String, goal: &ContractualGoal) {
        let vars = extract_variables(&goal.preconditions);
        let fn_name = to_snake_case(&goal.name);

        buf.push_str(&format!("pub fn {fn_name}<V>(\n"));
        buf.push_str("    verifier: &V,\n");

        if vars.is_empty() {
            buf.push_str("    // TODO(hammurabi): 引数を追加してください\n");
        } else {
            for v in &vars {
                buf.push_str(&format!(
                    "    {name}: i64, // TODO(hammurabi): 型を確認・修正してください\n",
                    name = v.name
                ));
            }
        }

        buf.push_str(") -> Result<LogicRail<i64>, VerificationError> // TODO(hammurabi): 戻り値の型を修正してください\n");
        buf.push_str("where\n");
        buf.push_str("    V: Verifier,\n");
        buf.push_str("{\n");
    }

    // -----------------------------------------------------------------------
    // 関数ボディ
    // -----------------------------------------------------------------------

    fn emit_body(&self, buf: &mut String, goal: &ContractualGoal) {
        let vars = extract_variables(&goal.preconditions);

        // ── LogicRail::bind 呼び出し ─────────────────────────────────────
        if !vars.is_empty() {
            buf.push_str("    // ── Precondition binds ─────────────────────────────────────────\n");
            for v in &vars {
                self.emit_bind(buf, v);
            }
            buf.push('\n');
        }

        // ── 不変条件コメント ──────────────────────────────────────────────
        if !goal.invariants.is_empty() {
            buf.push_str("    // ── Invariants (実行中ずっと成立させること) ──────────────────\n");
            for inv in &goal.invariants {
                buf.push_str(&format!("    // invariant: {inv}\n"));
            }
            buf.push('\n');
        }

        // ── 禁止パターンコメント ──────────────────────────────────────────
        buf.push_str("    // ── Forbidden Patterns (生成コードに含めてはならない) ───────────\n");
        for fp in &goal.forbidden {
            buf.push_str(&format!("    // ✗ {fp}\n"));
        }
        buf.push('\n');

        // ── todo! ─────────────────────────────────────────────────────────
        let ensures: Vec<String> = goal.postconditions.iter().map(|p| p.to_string()).collect();
        if ensures.is_empty() {
            buf.push_str(&format!("    todo!(\"Implement {name}\")\n", name = goal.name));
        } else {
            buf.push_str(&format!(
                "    // TODO(hammurabi): Postconditions を満たす実装を書いてください\n"
            ));
            for e in &ensures {
                buf.push_str(&format!("    // ensure: {e}\n"));
            }
            buf.push_str(&format!(
                "    todo!(\"Implement {name}: ensure {first}\")\n",
                name = goal.name,
                first = ensures[0],
            ));
        }

        buf.push_str("}\n");
    }

    /// 1 つの `VarInfo` から `LogicRail::bind(...)` 呼び出しを生成する。
    fn emit_bind(&self, buf: &mut String, v: &VarInfo) {
        buf.push_str(&format!(
            "    let {name} = LogicRail::bind(\n        \"{name}\",\n        {name},\n        vec![\n",
            name = v.name
        ));
        for c in &v.constraints {
            buf.push_str(&format!("            {c},\n"));
        }
        buf.push_str("        ],\n");
        buf.push_str("        verifier,\n");
        buf.push_str("    )?;\n");
    }
}

// ---------------------------------------------------------------------------
// ヘルパー関数
// ---------------------------------------------------------------------------

/// キャメルケース・スペースを snake_case に変換する（簡易実装）。
fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch == ' ' || ch == '-' {
            out.push('_');
        } else if ch.is_uppercase() && i > 0 {
            out.push('_');
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch.to_ascii_lowercase());
        }
    }
    out
}

/// `ForbiddenPattern` の日本語説明を返す。
fn forbidden_description(fp: &ForbiddenPattern) -> &'static str {
    match fp {
        ForbiddenPattern::NonExhaustiveBranch  => "全分岐を型レベルで網羅すること",
        ForbiddenPattern::RuntimeNullCheck     => "NonNull は型システムで証明すること",
        ForbiddenPattern::ImplicitCoercion     => "暗黙の型強制を禁止",
        ForbiddenPattern::UnprovenUnwrap       => "unwrap/expect は証明なしに使用禁止",
        ForbiddenPattern::CatchAllSuppression  => "_ パターンによるロジック隠蔽を禁止",
    }
}

// ---------------------------------------------------------------------------
// CodegenOutput — 生成されたソースコードの出力物
// ---------------------------------------------------------------------------

/// `CodeGenerator::generate` が返す出力物。
pub struct CodegenOutput {
    source: String,
}

impl CodegenOutput {
    /// 生成された Rust ソースコードの文字列を返す。
    pub fn source(&self) -> &str {
        &self.source
    }

    /// ファイルへ書き出す（wasm32 では利用不可）。
    #[cfg(not(target_arch = "wasm32"))]
    pub fn save_to_file(&self, path: impl AsRef<Path>) -> std::io::Result<()> {
        std::fs::write(path, &self.source)
    }
}

// ---------------------------------------------------------------------------
// テスト
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lang::goal::{ContractualGoal, ForbiddenPattern, Predicate};

    fn safe_division_goal() -> ContractualGoal {
        ContractualGoal::new("safe_division")
            .require(Predicate::non_null("divisor"))
            .require(Predicate::in_range("divisor", 1, i64::MAX))
            .require(Predicate::in_range("dividend", i64::MIN, i64::MAX))
            .ensure(Predicate::atom("result_is_finite"))
            .ensure(Predicate::atom("result_within_i64_range"))
            .invariant(Predicate::atom("no_memory_aliasing"))
            .forbid(ForbiddenPattern::RuntimeNullCheck)
    }

    #[test]
    fn generates_function_name_from_goal() {
        let output = CodeGenerator::new().generate(&safe_division_goal());
        assert!(output.source().contains("pub fn safe_division<V>"));
    }

    #[test]
    fn generates_doc_comment_with_all_sections() {
        let output = CodeGenerator::new().generate(&safe_division_goal());
        let src = output.source();
        assert!(src.contains("## Preconditions"));
        assert!(src.contains("## Postconditions"));
        assert!(src.contains("## Invariants"));
        assert!(src.contains("## Forbidden Patterns"));
    }

    #[test]
    fn generates_logic_rail_bind_for_each_variable() {
        let output = CodeGenerator::new().generate(&safe_division_goal());
        let src = output.source();
        // divisor と dividend の bind が存在すること
        assert!(src.contains("let divisor = LogicRail::bind("));
        assert!(src.contains("let dividend = LogicRail::bind("));
    }

    #[test]
    fn generates_constraint_non_null() {
        let output = CodeGenerator::new().generate(&safe_division_goal());
        assert!(output.source().contains("Constraint::NonNull"));
    }

    #[test]
    fn generates_constraint_in_range() {
        let output = CodeGenerator::new().generate(&safe_division_goal());
        let src = output.source();
        assert!(src.contains("Constraint::InRange { min: 1_i64"));
        assert!(src.contains("Constraint::InRange { min:"));
    }

    #[test]
    fn generates_todo_with_postcondition() {
        let output = CodeGenerator::new().generate(&safe_division_goal());
        assert!(output.source().contains("todo!(\"Implement safe_division: ensure result_is_finite\")"));
    }

    #[test]
    fn generates_forbidden_pattern_comments() {
        let output = CodeGenerator::new().generate(&safe_division_goal());
        let src = output.source();
        assert!(src.contains("✗ RuntimeNullCheck"));
        assert!(src.contains("✗ NonExhaustiveBranch"));
    }

    #[test]
    fn generated_code_is_human_readable() {
        let output = CodeGenerator::new().generate(&safe_division_goal());
        let src = output.source();

        // 生成コードの全体を出力（目視確認用）
        println!("{src}");

        // 最低限の構造チェック
        assert!(src.contains("use hammurabi::compiler::verifier"));
        assert!(src.contains("use hammurabi::lang::rail"));
        assert!(src.contains("where\n    V: Verifier,"));
    }

    #[test]
    fn compound_predicate_and_extracts_both_branches() {
        let goal = ContractualGoal::new("check")
            .require(Predicate::and(
                Predicate::non_null("x"),
                Predicate::in_range("x", 0, 100),
            ))
            .ensure(Predicate::atom("x_valid"));

        let output = CodeGenerator::new().generate(&goal);
        let src = output.source();
        // And の両ブランチが同じ変数 x に集約されること
        assert!(src.contains("let x = LogicRail::bind("));
        assert!(src.contains("Constraint::NonNull"));
        assert!(src.contains("Constraint::InRange { min: 0_i64, max: 100_i64 }"));
    }

    #[test]
    fn snake_case_conversion() {
        assert_eq!(to_snake_case("SafeDivision"), "safe_division");
        assert_eq!(to_snake_case("safe_division"), "safe_division");
        assert_eq!(to_snake_case("safe division"), "safe_division");
    }

    #[test]
    fn save_to_file_writes_valid_rust_source() {
        let output = CodeGenerator::new().generate(&safe_division_goal());
        let path = std::env::temp_dir().join("hammurabi_codegen_test.rs");
        output.save_to_file(&path).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("pub fn safe_division"));
        std::fs::remove_file(path).ok();
    }
}
