//! Generated by Hammurabi — do not edit manually.
//! Edit the `ContractualGoal` definition instead.
//!
//! ContractualGoal: `math`

#![allow(unused_variables, dead_code)]

use crate::compiler::verifier::{Verifier, VerificationError};
use crate::lang::rail::{Constraint, LogicRail};

/// # Contract: `math`
///
/// *Generated by [Hammurabi](https://github.com/hammurabi-lang/hammurabi)*
///
/// ## Preconditions — 呼び出し元が保証すること
/// - `(-2147483648 ≤ x ≤ 2147483648 ∧ -2147483648 ≤ y ≤ 2147483648)`
///
/// ## Postconditions — この関数が保証すること
/// - `result_within_i64_range`
///
/// ## Proof
/// x, y が共に i32 範囲 [-2^31, 2^31] に収まるとき、
/// x + y の最大値は 2^32 ≤ i64::MAX = 2^63 - 1 であるため
/// 加算結果は i64 範囲に論理的帰結として収まる。
///
/// ## Forbidden Patterns
/// - `NonExhaustiveBranch` — 全分岐を型レベルで網羅すること
/// - `UnprovenUnwrap`       — unwrap/expect は証明なしに使用禁止
/// - `CatchAllSuppression`  — `_` パターンによるロジック隠蔽を禁止
///
pub fn math<V: Verifier>(
    verifier: &V,
    x: i64,
    y: i64,
) -> Result<LogicRail<i64>, VerificationError> {
    // ── Precondition binds ────────────────────────────────────────────────
    // x, y を i32 範囲に封印。この bind が失敗した時点でコンパイル後でも安全に止まる。
    let x_rail = LogicRail::bind(
        "x",
        x,
        vec![Constraint::InRange { min: -2_147_483_648_i64, max: 2_147_483_648_i64 }],
        verifier,
    )?;
    let y_rail = LogicRail::bind(
        "y",
        y,
        vec![Constraint::InRange { min: -2_147_483_648_i64, max: 2_147_483_648_i64 }],
        verifier,
    )?;

    // ── Implementation ────────────────────────────────────────────────────
    // x_rail と y_rail は証明済みの値なので extract() は安全。
    // 加算結果を i64 全域制約で再封印することで postcondition を型として表明する。
    let sum = x_rail.extract() + y_rail.extract();

    LogicRail::bind(
        "result",
        sum,
        vec![Constraint::InRange { min: i64::MIN, max: i64::MAX }],
        verifier,
    )
}

// ---------------------------------------------------------------------------
// テスト
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiler::verifier::MockVerifier;

    #[test]
    fn math_adds_two_positive_numbers() {
        let v      = MockVerifier::default();
        let result = math(&v, 3, 4).unwrap();
        assert_eq!(*result.extract(), 7);
    }

    #[test]
    fn math_handles_negative_numbers() {
        let v      = MockVerifier::default();
        let result = math(&v, -100, 50).unwrap();
        assert_eq!(*result.extract(), -50);
    }

    #[test]
    fn mock_rejects_out_of_range_input() {
        // MockVerifier は値レベルチェックを行うため、i32 範囲外の値を弾く
        let v      = MockVerifier::default();
        let result = math(&v, 3_000_000_000_i64, 1);
        assert!(result.is_err(), "MockVerifier は i32 範囲外の値を弾くべき");
    }

    /// Z3Verifier は具体値エンコードにより範囲外入力を UNSAT として拒否する
    #[cfg(feature = "z3-backend")]
    #[test]
    fn z3_rejects_out_of_range_input() {
        use crate::compiler::verifier::z3_backend::Z3Verifier;
        let v      = Z3Verifier::new();
        // x = 3_000_000_000 ∧ -2^31 ≤ x ≤ 2^31  →  UNSAT
        let result = math(&v, 3_000_000_000_i64, 1);
        assert!(result.is_err(), "Z3Verifier は i32 範囲外の値を UNSAT として弾くべき");
    }

    /// prove_invariant を使った具体値レベルの範囲証明デモ
    #[cfg(feature = "z3-backend")]
    #[test]
    fn z3_prove_invariant_detects_out_of_range() {
        use crate::compiler::verifier::z3_backend::Z3Verifier;
        use crate::lang::goal::Predicate;

        let v = Z3Verifier::new();
        // 「x = 3_000_000_000 かつ x ∈ [-2^31, 2^31]」は矛盾 → Disproven
        let status = v.prove_invariant(
            &[Predicate::in_range("x", 3_000_000_000, 3_000_000_000)], // x の具体値を固定
            &Predicate::in_range("x", -2_147_483_648, 2_147_483_648),  // i32 範囲に収まるか
        ).unwrap();
        assert!(matches!(status, crate::compiler::verifier::ProofStatus::Disproven { .. }),
            "x=3_000_000_000 は i32 範囲外なので Disproven になるべき");
    }

    #[test]
    fn math_boundary_values() {
        let v      = MockVerifier::default();
        let result = math(&v, 2_147_483_648, -2_147_483_648).unwrap();
        assert_eq!(*result.extract(), 0);
    }
}
